#version 450

layout(set = 0, binding = 0, rgba8) uniform writeonly image2D outputImage;

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
void main()
{
	ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 textureSize = imageSize(outputImage);
	vec2 normalizedCoord = vec2(pixelCoord) / vec2(textureSize);

	vec4 color = vec4(normalizedCoord, 0.0f, 1.0f);

    imageStore(outputImage, pixelCoord, color);
}
