name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Display the path
        shell: cmd
        run: cd Pengine-2.0 && mkdir Build && cd Build && cmake ..
