name: C/C++ CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Setup Environment (PR)  
        if: ${{ github.event_name == 'pull_request' }}  
        shell: bash  
        run: |  
          echo "LAST_COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}  
      - name: Setup Environment (Push)  
        if: ${{ github.event_name == 'push' }}  
        shell: bash  
        run: |
          echo "LAST_COMMIT_SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}
      - name: Create Folder
        run: mkdir LAST_COMMIT_SHA | cd LAST_COMMIT_SHA
      - name: Clone
        run: git clone --recursive -b main https://github.com/Shturm0weak/Pengine-2.0.git
      - name: Build
        run: cd Pengine-2.0 | mkdir Build | cd Build | cmake ..
      - name: Compile
        run: \"C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/devenv.exe" Pengine.sln /Build Release
      - name: Test
        run: cd Test/Build/Release | Test.exe
